apiVersion: v1
kind: Pod
metadata:
  name: nodejs-shell
spec:
  serviceAccountName: kube-client-agent
  containers:
  - name: nodejs-shell
    image: nodejs-shell:1.0
    command: [ "tail", "-f", "/dev/null" ]
